apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  # setting of bitnami/redis image
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password
  - name: queryIndexes
    value: |
      [
        {
          "name": "helloIndx",
          "indexes": [
            {
              "key": "msg",
              "type": "TEXT"
            }
          ]
        },
        {
          "name": "personIndx",
          "indexes": [
            {
              "key": "age",
              "type": "NUMERIC"
            },
            {
              "key": "name.first",
              "type": "TEXT"
            },
            {
              "key": "name.last",
              "type": "TEXT"
            },
            {
              "key": "friends[0]",
              "type": "TEXT"
            }
          ]
        }
      ]
auth:
  secretStore: kubernetes
